/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2025-02-08 13:08:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Dashboard</title>\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("         body {\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding: 0;\r\n");
      out.write("                background-image: url('https://i.postimg.cc/nzB5N9H5/Dashboard.jpg'); /* Background image for the page */\r\n");
      out.write("                background-size: cover;\r\n");
      out.write("                background-position: center;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: center; /* Center horizontally */\r\n");
      out.write("                align-items: center; /* Center vertically */\r\n");
      out.write("                height: 100vh;\r\n");
      out.write("            }\r\n");
      out.write("        .account-container {\r\n");
      out.write("            background: rgba(71, 70, 70, 0.3);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        .account-detail {\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        .account-detail strong {\r\n");
      out.write("            color: #cfcfcf;\r\n");
      out.write("        }\r\n");
      out.write("        .form{\r\n");
      out.write("         position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("            background: rgba(71, 70, 70, 0.3); /* Transparent background */\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            max-width: 360px;\r\n");
      out.write("            padding: 45px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);\r\n");
      out.write("            }\r\n");
      out.write("            .header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-around; /* Space buttons evenly */\r\n");
      out.write("            align-items: center; /* Center buttons vertically */\r\n");
      out.write("            background: rgba(71, 70, 70, 0.5); /* Semi-transparent background */\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3); /* Shadow effect */\r\n");
      out.write("            width: 100%; /* Full width */\r\n");
      out.write("            position: fixed; /* Fix the header at the top */\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            z-index: 1000; /* Ensure header is above other content */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header button {\r\n");
      out.write("            font-family: \"Roboto\", sans-serif;\r\n");
      out.write("            background: #07336b;\r\n");
      out.write("            color: #FFFFFF;\r\n");
      out.write("            \r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header button:hover, .header button:active, .header button:focus {\r\n");
      out.write("            background: #071041;\r\n");
      out.write("        }\r\n");
      out.write("        .form input {\r\n");
      out.write("            font-family: \"Roboto\", sans-serif;\r\n");
      out.write("            outline: 0;\r\n");
      out.write("            background: #f2f2f2;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border: 0;\r\n");
      out.write("            margin: 0 0 15px;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form button {\r\n");
      out.write("            font-family: \"Roboto\", sans-serif;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            outline: 0;\r\n");
      out.write("            background: #07336b;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border: 0;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            color: #FFFFFF;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form button:hover, .form button:active, .form button:focus {\r\n");
      out.write("            background: #071041;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form .message {\r\n");
      out.write("            margin: 15px 0 0;\r\n");
      out.write("            color: #999191;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form .message a {\r\n");
      out.write("            color: #77a5e6;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        .login-page {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center; /* Center horizontally */\r\n");
      out.write("            align-items: center; /* Center vertically */\r\n");
      out.write("            flex: 1; /* Take up remaining space below the header */\r\n");
      out.write("            margin-top: 60px; /* Adjust for the height of the fixed header */\r\n");
      out.write("            height: calc(100vh - 60px); /* Ensure full height minus header height */\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("      <script>\r\n");
      out.write("        // Reload the page every 30 seconds\r\n");
      out.write("        setTimeout(function(){\r\n");
      out.write("            window.location.reload(1);\r\n");
      out.write("        }, 30000);\r\n");
      out.write("\r\n");
      out.write("        function performOperationAndReload() {\r\n");
      out.write("            // Execute your operation here\r\n");
      out.write("\r\n");
      out.write("            // After operation completes, reload the page\r\n");
      out.write("            window.location.reload();\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <button id=\"transactionButton\" onclick=\"window.location.href='transfer.jsp';\" onclick=\"performOperationAndReload()\">Transaction</button>\r\n");
      out.write("        <button id=\"Withdrawal\" onclick=\"window.location.href='withdrawal.jsp';\">Withdraw</button>\r\n");
      out.write("        <button id=\"Deposit\" onclick=\"window.location.href='depositing.jsp';\">Deposit</button>\r\n");
      out.write("        <button id=\"Logout\" onclick=\"window.location.href='index.jsp';\">Logout</button>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"login-page\">\r\n");
      out.write("        <div class=\"form\">\r\n");
      out.write("            <h2>Your Account Details</h2>\r\n");
      out.write("            <c:forEach var=\"account\" items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accounts}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                <div class=\"account-container\">\r\n");
      out.write("                    <div class=\"account-detail\"><strong>Account Number:</strong> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account.accno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    <div class=\"account-detail\"><strong>Account Type:</strong> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account.acc_type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    <div class=\"account-detail\"><strong>Name:</strong> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    <div class=\"account-detail\"><strong>Balance:</strong> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account.balance}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    \r\n");
      out.write("            </c:forEach>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
