/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2025-02-08 13:06:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Login Page</title>\r\n");
      out.write("    <style>\r\n");
      out.write("    @import url('https://fonts.googleapis.com/css?family=Roboto:300');\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        background-image: url('https://i.postimg.cc/nzB5N9H5/Dashboard.jpg'); /* Background image for the page */\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center; /* Center horizontally */\r\n");
      out.write("        align-items: center; /* Center vertically */\r\n");
      out.write("        height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .main-box {\r\n");
      out.write("        width: 360px;\r\n");
      out.write("        background: rgba(71, 70, 70, 0.3); /* Transparent background */\r\n");
      out.write("        backdrop-filter: blur(10px);\r\n");
      out.write("        padding: 45px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .main-box h3 {\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("        font-family: Tahoma,verdana,sans-serif;\r\n");
      out.write("\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-box {\r\n");
      out.write("        display: grid;\r\n");
      out.write("        grid-template-columns: repeat(2, 1fr); /* Two columns for buttons */\r\n");
      out.write("        gap: 10px; /* Spacing between buttons */\r\n");
      out.write("        margin-bottom: 20px; /* Space between button grid and exit button */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    button {\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        background-color: #1f4c76; /* Default button background color */\r\n");
      out.write("        border-color: rgb(90, 126, 126);\r\n");
      out.write("        color: #FFFFFF;\r\n");
      out.write("        cursor: pointer; /* Change cursor to pointer on hover */\r\n");
      out.write("        transition: background-color 0.3s; /* Smooth background color transition */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    button:hover {\r\n");
      out.write("        background-color: #1c5abf; /* Darker background on hover */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .exit {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .exit button {\r\n");
      out.write("        width: 150px;\r\n");
      out.write("        background-color: #41474e; /* Background color for Exit button */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .exit button:hover {\r\n");
      out.write("        background-color: #2a3741; /* Darker background on hover */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("    <div class=\"main-box\">\r\n");
      out.write("    <center><h3>Logo Banking</h3></center>\r\n");
      out.write("        <div class=\"btn-box\">\r\n");
      out.write("            <button id=\"check-balance-btn\" onclick=\"window.location.href='balance.jsp';\"> Balance </button>\r\n");
      out.write("            <button id=\"Deposit-btn\" onclick=\"window.location.href='deposit.jsp';\"> Deposit </button>\r\n");
      out.write("            <button id=\"Withdraw-btn\" onclick=\"window.location.href='withdraw.jsp';\"> Withdraw </button>\r\n");
      out.write("            <button id=\"Changepass-btn\" onclick=\"window.location.href='Changepass.jsp';\"> Changepass </button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"exit\">\r\n");
      out.write("        <button id=\"btn-Exit\" onclick=\"window.location.href='index.jsp';\"> Exit </button>\r\n");
      out.write("    </div>\r\n");
      out.write("<div>\r\n");
      out.write("  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("  <script  src=\"js/index.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
