/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2025-02-08 13:06:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Login Page</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css?family=Roboto:300');\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-image: url('https://i.postimg.cc/5tFkFQF0/login.jpg');\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: flex-end; /* Align to the right */\r\n");
      out.write("            align-items: flex-start; /* Align to the top */\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-page {\r\n");
      out.write("            width: 360px;\r\n");
      out.write("            margin-right: 175px; /* Space between container and right edge */\r\n");
      out.write("            margin-top: 200px; /* Space between container and top of the screen */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("            background: rgba(71, 70, 70, 0.3); /* Transparent background */\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            max-width: 360px;\r\n");
      out.write("            margin: 0 auto 100px;\r\n");
      out.write("            padding: 45px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form input {\r\n");
      out.write("            font-family: \"Roboto\", sans-serif;\r\n");
      out.write("            outline: 0;\r\n");
      out.write("            background: #f2f2f2;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border: 0;\r\n");
      out.write("            margin: 0 0 15px;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form button {\r\n");
      out.write("            font-family: \"Roboto\", sans-serif;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            outline: 0;\r\n");
      out.write("            background: #156ab9;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border: 0;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            color: #FFFFFF;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            -webkit-transition: all 0.3s ease;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form button:hover, .form button:active, .form button:focus {\r\n");
      out.write("            background: #283365;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form .message {\r\n");
      out.write("            margin: 25px 0 0;\r\n");
      out.write("            color: #b3b3b3;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form .message a {\r\n");
      out.write("            color: #156ab9;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form .register-form {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"login-page\">\r\n");
      out.write("        <div class=\"form\">\r\n");
      out.write("            <form class=\"login-form\" action=\"LoginServlet\" method=\"post\">\r\n");
      out.write("		    <input type=\"text\" name=\"username\" placeholder=\"username\" required/>\r\n");
      out.write("		    <input type=\"password\" name=\"password\" placeholder=\"password\" required/>\r\n");
      out.write("		    <button type=\"submit\">SIGN IN</button>\r\n");
      out.write("		    <p class=\"message\">Not registered? <a href=\"create.jsp\">Create an account</a></p>\r\n");
      out.write("		    <p class=\"message\">Not registered? <a href=\"home.jsp\">With-Out Login(As a guest)</a></p>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\r\n");
      out.write("    <script src=\"js/index.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
